# Default values for terraform-operator.

# controller - vars for deployment and service of the server
controller:
  # controller.enabled -- deploy the terraform-operator controller
  enabled: true

  # controller.replicaCount -- number of replicas
  replicaCount: 1

  image:
    # controller.image.repository -- image without the tag.
    repository: isaaguilar/terraform-operator
    # controller.image.tag -- tag of the image
    tag: v0.9.0-alpha6
    # controller.image.pullPolicy -- Set how kubernetes determines when
    # to pull the docker image.
    pullPolicy: IfNotPresent

  # controller.args -- additional arguments for the command
  # @default -- <a href="values.yaml#L22-L24">values.yaml</a>
  args:
  - --zap-log-level=debug
  - --zap-encoder=console
  ## Uncomment the following to allow the controller to create multiple threads
  ## when workflow pods get queued.
  # - --max-concurrent-reconciles=10

  # controller.resources -- CPU/Memory request and limit configuration
  # @default -- <a href="values.yaml#L31-L37">values.yaml</a>
  resources:
    limits:
      cpu: 50m
      memory: 128M
    requests:
      cpu: 25m
      memory: 64M

  securityContext:
    # -- Allow running as root when false
    runAsNonRoot: true
    # -- All processes run with user specified. This can be set to null for use on openshift
    runAsUser: 1001

  # controller.environmentVars -- key/value envs
  environmentVars: {}

  # -- Env defined like k8s EnvVar https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#envvar-v1-core.
  # Accepts `tpl` values.
  env: []

  # controller.nodeSelector -- node labels for pod assignment
  nodeSelector: {}

  # controller.tolerations -- List of node taints to tolerate
  tolerations: []

  # controller.affinity -- node/pod affinities
  affinity: {}

# - webhooks options
webhook:
  # -- enables the webhook - required most of the time
  enabled: true

  # -- number of replicas for the webhook
  replicaCount: 2

  image:
    # -- image without the tag. Usually the same as the controller
    repository: isaaguilar/terraform-operator
    # -- tag of the image
    tag: v0.9.0-alpha6
    # -- Set how kubernetes determines when to pull the docker image.
    pullPolicy: IfNotPresent

  # -- additional arguments for the command
  # @default -- <a href="values.yaml#L79">values.yaml</a>
  args:
  - --zap-log-level=debug
  - --zap-encoder=console

  # -- CPU/Memory request and limit configuration
  # @default -- <a href="values.yaml#L85">values.yaml</a>
  resources:
    requests:
      cpu: 25m
      memory: 64M

  securityContext:
    # -- Allow running as root when false
    runAsNonRoot: true
    # -- All processes run with user specified. This can be set to null for use on openshift
    runAsUser: 1001

  # -- key/value envs
  environmentVars: {}

  # -- Env defined like k8s EnvVar https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#envvar-v1-core.
  # Accepts `tpl` values.
  env: []

  # -- node labels for pod assignment
  nodeSelector: {}

  # -- List of node taints to tolerate
  tolerations: []

  # -- node/pod affinities
  # @default -- <a href="values.yaml#L110">values.yaml</a>
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: release
              operator: In
              values:
              - "{{ .Release.Name }}"
            - key: component
              operator: In
              values:
              - webhook
          topologyKey: kubernetes.io/hostname
        weight: 100