# -- Optional args to include for the command
args:
- use-service-host

# -- Env defined like k8s EnvVar https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#envvar-v1-core.
env: []
# - name: DASHBOARD
#   value: https://<dashboard-host>
# - name: JWT_SIGNING_KEY
#   value: chamgeMePle!ase
# - name: ADMIN_USERNAME
#   value: isa
# - name: ADMIN_PASSWORD
#   value: $2a$10$2ap6bphr5ZBkEMTBb/ZoT.zrY7lUwzCW2u1n5tIeVugtVpjMRW9Fe

# Image options
image:
  # The container image tag
  tag: 0.8.1

# - Options for the api-webserver
server:
  # -- The port the runtime exposes to connect to the webserver
  port: 5555

# - Service options to expose the API
service:
  # -- Service annotations key/values for the service resource
  annotations: {}
  # -- the http or https port clients will use to access the `server.port`
  port: 80
  # -- service type is one of ClusterIP | LoadBalancer | NodePort
  type: ClusterIP


# -- CPU/Memory request and limit configuration
resources: {}

# -- node labels for pod assignment
nodeSelector: {}

# -- List of node taints to tolerate
tolerations: []

# -- node/pod affinities
affinity: {}

# -- Create a pvc backed postgres database. Not suitable for production use.
# @default -- `enabled=false`
postgres:
  enabled: false
  name: terraform-operator-api-postgres
  server:
    port: 5432
    storage: "100Mi"
  database:
    name: tfoapi
  user:
    username: admin
    password: password
