# -- image repository and tag
image:
  repository: ghcr.io/galleybytes/terraform-operator-remote-controller
  tag: 1.0.0

# -- Env defined like k8s EnvVar https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#envvar-v1-core.
env: []
# - name: CLIENT_NAME
#   value: cluster-x
# - name: TFO_API_PROTOCOL
#   value: http
# - name: TFO_API_HOST
#   value: terraform-operator-api.tf-system.svc
# - name: TFO_API_PORT
#   value: "80"
# - name: TFO_API_LOGIN_USER
#   value: admin
# - name: TFO_API_LOGIN_PASSWORD
#   value: password

# -- CPU/Memory request and limit configuration
resources:
  limits:
    cpu: 50m
    memory: 32M
  requests:
    cpu: 5m
    memory: 32M

# -- node labels for pod assignment
nodeSelector: {}

# -- List of node taints to tolerate
tolerations: []

# -- node/pod affinities
affinity: {}