apiVersion: v1
kind: Service
metadata:
  annotations:
  {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  labels:
    app.kubernetes.io/name: terraform-operator-remote-controller
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Values.image.tag }}
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: terraform-operator
    app.kubernetes.io/managed-by: helm
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  name: {{ .Release.Name }}
spec:
  ports:
  - name: https
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.server.port }}
  selector:
    app: {{ .Release.Name }}
    component: controller
  type: {{ .Values.service.type }}
