{{- if .Values.controller.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ template "_chart.label" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: controller
  {{- with .Values.controller.serviceAccount.extraAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
