apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-webhook
  labels:
    app: {{ .Chart.Name }}
    chart: {{ template "_chart.label" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: webhook