apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: terraform-operator-remote-controller
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Values.image.tag }}
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: terraform-operator
    app.kubernetes.io/managed-by: helm
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
rules:
- apiGroups:
  - tf.galleybytes.com
  resources:
  - 'terraforms'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - update
