apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      service: terraform-operator
      component: api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: terraform-operator
        component: api
    spec:
      serviceAccount: {{ .Release.Name }}
      containers:
      - {{ with .Values.args -}}
        args:
          {{- toYaml . | nindent 8 }}
        {{ end -}}
        envFrom:
        {{- with .Values.envFrom }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.secret }}
        - secretRef:
            name: {{ .Release.Name }}
        {{- end }}
        env:
        - name: SERVICE_NAME
          value: {{ .Release.Name }}
        {{- if .Values.postgres.enabled }}
        - name: DB_URL
          value: postgres://{{ .Values.postgres.user.username }}:{{ .Values.postgres.user.password }}@{{ .Values.postgres.name }}.{{ .Release.Namespace }}.svc:5432/{{ .Values.postgres.database.name }}
        {{- end }}
        - name: PORT
          value: 0.0.0.0:{{ .Values.server.port }}
        {{- range .Values.env }}
        - name: {{ .name }}
          value: {{ .value }}
        {{- end }}
        image: ghcr.io/galleybytes/terraform-operator-api:{{ .Values.image.tag }}
        imagePullPolicy: IfNotPresent
        name: api
        ports:
        - containerPort: {{ .Values.server.port }}
          protocol: TCP
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      restartPolicy: Always
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
