{{ if .Values.postgres.enabled }}
apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/instance: postgres-tfoapi
        app.kubernetes.io/version: 12.8.1
        app.kubernetes.io/component: database
        app.kubernetes.io/part-of: terraform-operator-api
        app.kubernetes.io/managed-by: helm
      name: {{ .Values.postgres.name }}
    spec:
      ports:
        - name: "{{ .Values.postgres.server.port }}"
          port: {{ .Values.postgres.server.port }}
          targetPort: {{ .Values.postgres.server.port }}
      selector:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/instance: postgres-tfoapi
        app.kubernetes.io/version: 12.8.1
        app.kubernetes.io/component: database
        app.kubernetes.io/part-of: terraform-operator-api
        app.kubernetes.io/managed-by: helm
    status:
      loadBalancer: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/instance: postgres-tfoapi
        app.kubernetes.io/version: 12.8.1
        app.kubernetes.io/component: database
        app.kubernetes.io/part-of: terraform-operator-api
        app.kubernetes.io/managed-by: helm
      name: {{ .Values.postgres.name }}
    spec:
      replicas: 1
      selector:
        matchLabels:
          app.kubernetes.io/name: postgres
          app.kubernetes.io/instance: postgres-tfoapi
          app.kubernetes.io/version: 12.8.1
          app.kubernetes.io/component: database
          app.kubernetes.io/part-of: terraform-operator-api
          app.kubernetes.io/managed-by: helm
      strategy:
        type: Recreate
      template:
        metadata:
          creationTimestamp: null
          labels:
            app.kubernetes.io/name: postgres
            app.kubernetes.io/instance: postgres-tfoapi
            app.kubernetes.io/version: 12.8.1
            app.kubernetes.io/component: database
            app.kubernetes.io/part-of: terraform-operator-api
            app.kubernetes.io/managed-by: helm
        spec:
          initContainers:
            - args:
                - -rf
                - /var/lib/postgresql/data/lost+found
              command:
                - rm
              image: busybox:latest
              imagePullPolicy: IfNotPresent
              name: cleanup
              securityContext:
                privileged: true
              volumeMounts:
                - mountPath: /var/lib/postgresql/data
                  name: db
          containers:
            - env:
                - name: POSTGRES_DB
                  value: {{ .Values.postgres.database.name }}
                - name: POSTGRES_PASSWORD
                  value: {{ .Values.postgres.user.password }}
                - name: POSTGRES_USER
                  value: {{ .Values.postgres.user.username }}
              image: postgres:12.8
              name: {{ .Values.postgres.name }}
              ports:
                - containerPort: {{ .Values.postgres.server.port }}
              resources: {}
              volumeMounts:
                - mountPath: /var/lib/postgresql/data
                  name: db
          restartPolicy: Always
          volumes:
            - name: db
              persistentVolumeClaim:
                claimName: {{ .Values.postgres.name }}
    status: {}
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/instance: postgres-tfoapi
        app.kubernetes.io/version: 12.8.1
        app.kubernetes.io/component: database
        app.kubernetes.io/part-of: terraform-operator-api
        app.kubernetes.io/managed-by: helm
      name: {{ .Values.postgres.name }}
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.postgres.server.storage }}
    status: {}
kind: List
metadata: {}

{{ end }}
