apiVersion: v1
kind: Service
metadata:
  labels:
    service: terraform-operator
    component: api
  name: {{ .Values.deployment }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: {{ .Values.server.port }}
  selector:
    service: terraform-operator
    component: api
  type: ClusterIP
