apiVersion: v1
kind: Service
metadata:
  labels:
    service: terraform-operator
    component: api
  name: {{ .Release.Name }}
spec:
  ports:
  - name: http
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.server.port }}

  selector:
    service: terraform-operator
    component: api
  type: {{ .Values.service.type }}
